name: n8n-app-do
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
region: nyc
services:
- envs:
  - key: WEBHOOK_URL
    scope: RUN_AND_BUILD_TIME
    value: ${_self.PUBLIC_URL}
  name: web-service
  http_port: 5678
  image:
    registry: matthijs166
    registry_type: DOCKER_HUB
    repository: n8n-websocket
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  run_command: n8n
